.\" cencode.1: cencode manual
.\" Copyright(c) 2006 by wave++ "Yuri D'Elia" <wavexx@users.sf.net>
.\" Distributed under Revised BSD license (see COPYING) WITHOUT ANY WARRANTY.
.\"
.Dd January 27, 2008
.Dt CENCODE 1
.\"
.\"
.Sh NAME
.Nm cencode
.Nd encode a stream into c-string escape sequences
.\"
.\"
.Sh SYNOPSIS
.Nm
.Op Fl hrp
.Op Fl c Ar columns
.Op Fl q Ar qualifiers
.Op Fl s Ar symbol
.Op Ar file ...
.\"
.\"
.Sh DESCRIPTION
.Nm
encodes a stream or a file into quoted c-string escape sequences, suitable for
use directly into C code.
.Pp
.Nm
is an universal alternative to dedicated export formats like XPM, unportable
resource forks, linker flags and windows resources where dynamic loading of
external data is not possible or undesired.
.\"
.\"
.Sh OPTIONS
.\"
.Bl -tag -compact
.It Fl h
Display short usage information.
.It Fl r
When
.Fl s
is specified, output data in "readable" format. Output is spaced, indented and
wrapped automatically at 79 columns.
.It Fl p
When
.Fl s
is specified, output data in "packed" format. No spacing or indent is used, and
lines are wrapped at 255 columns in order to save space. This is the default.
.It Fl c Ar columns
When
.Fl s
is specified, wrap the output (last printable character) at the specified
number of columns. Defaults to 79 in readable format or 255 in packed format.
.It Fl q Ar qualifiers
When
.Fl s
is specified, specify the symbol qualifiers. The default is "const".
.It Fl s Ar sym
Output the whole sequence as a quoted C symbol named sym.
.El
.Pp
If no files are specified,
.Nm
reads the stream from standard input.
.Pp
When no symbol name is specified,
.Nm
outputs the encoded stream as if surrounded by quotes in a single line of
infinite length, ideal for post-processing. No final newline is produced.
.\"
.\"
.Sh EXAMPLES
Convert the file
.Pa data
into the named string
.Ar dataString
.Pp
.Dl cencode -s dataString data > file.c
.Pp
Encode multiple files into a single string:
.Pp
.Dl cat file1 file2 file3 | cencode -s sym > file.c
.\"
.\"
.Sh NOTES
Embedding unstructured binary content into executables should be avoided at all
costs.
.Pp
The output generated by wrapping lines beyond 255 columns may not be readable
by all compilers, text editors or tools.
.\"
.\"
.Sh DIAGNOSTICS
.Ex -std
.\"
.\"
.Sh SEE ALSO
.Xr lzo 1
.\"
.\"
.Sh AUTHORS
.Nm
is distributed under Revised BSD license (see COPYING)
.Em WITHOUT ANY WARRANTY .
Copyright(c) 2006 by
.An "Yuri D'Elia" Aq wavexx@users.sf.net .
